name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install xmlstarlet
      run: sudo apt-get install -y xmlstarlet
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run tests
      run: mvn test
    - name: Capture Test Results
      if: failure()
      run: |
        mkdir -p ${{ github.workspace }}/test-results
        for file in ${GITHUB_WORKSPACE}/target/surefire-reports/*.xml; do
          echo "Failed tests in $file:" >> ${{ github.workspace }}/test-results/failed_tests_summary.txt
          xmlstarlet sel -t -m "//testcase[failure]" -v "concat('Test: ', @name, ' - Error: ', failure/@message)" -n $file >> ${{ github.workspace }}/test-results/failed_tests_summary.txt
        done
    - name: Display Test Results
      if: failure()
      run: cat ${{ github.workspace }}/test-results/failed_tests_summary.txt
    - name: Telegram Notification on Failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Некоторые тесты не пройдены. См. подробности"
        document: "${{ github.workspace }}/test-results/failed_tests.txt"
    - name: Telegram Notification on Success
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Все ок"
