name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run tests
      run: mvn test
    - name: Capture Test Results
      if: failure()
      run: |
        mkdir -p ${{ github.workspace }}/test-results
        for file in ${GITHUB_WORKSPACE}/target/surefire-reports/*.xml; do
          # Extracting the names and messages of failed tests
          echo "Failed tests in $file:" >> ${{ github.workspace }}/test-results/failed_tests_summary.txt
          grep -oP '(?<=<testcase).*?(?=</testcase>)' $file | grep -Pzo '(?s)<testcase.*?name=".*?".*?<failure.*?>(.*?)</failure>' | while IFS= read -r match; do
            test_name=$(echo $match | grep -oP '(?<=name=").*?(?=")')
            error_message=$(echo $match | grep -oP '(?<=<failure message=").*?(?=")')
            echo "Test: $test_name" >> ${{ github.workspace }}/test-results/failed_tests_summary.txt
            echo "Error: $error_message" >> ${{ github.workspace }}/test-results/failed_tests_summary.txt
            echo "" >> ${{ github.workspace }}/test-results/failed_tests_summary.txt
          done
        done
    - name: Telegram Notification on Failure  # Отправка уведомления в Telegram в случае ошибки
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Некоторые тесты не пройдены. См. подробности:"
        document: "${{ github.workspace }}/test-results/failed_tests_summary.txt"
    - name: Telegram Notification on Success  # Отправка уведомления в Telegram, если все тесты прошли успешно
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Все ок"
